#!/usr/bin/perl

$\ = "\n";

my $state;

undef $state;

while (<>) {

    /logger\.(\w+)\(\s*"(\w+)/ && do {
        print "$ARGV:$.: $1 $2";
        next;
    };

    /logger\.(\w+)\(\s*$/ && do {
        $state = "$ARGV:$.: $1";
        next;
    };
    
    /(LogSpan)\(logger,\s*"(\w+)/ && do {
        print "$ARGV:$.: $1 $2";
        next;
    };

    /(LogSpan)\(\s*$/ && do {
        $state = "$ARGV:$.: $1";
        next;
    };

    /^\s*"(\w+)/ && do {
        if ($state) {
            print "$state $1";
        }
        undef $state;
        next;
    };

    /^\s*logger,\s*"(\w+)/ && do {
        if ($state) {
            print "$state $1";
        }
        undef $state;
        next;
    };

    /\S/ && do {
        undef $state;
        next;
    };
    
} continue {
    if (eof(ARGV)) {
        undef $state;
        close ARGV;
    }
}
