#!/usr/bin/env perl

$\ = "\n ";


@positive = (
             "Sir?",
             "You rang?",
             "Yes?",
             "How may I be of assistance?",
             "Awaiting instructions.",
             "Would you like to play a game?",
             "You are in a maze of twisty passages, all alike.",
             "TURBO mode activated.",
             "Go go go!",
             "This! Is! A! Meaningless! Sentence!",
             "Excellent.",
            );


@negative = (
             "Perhaps not, sir.",
             "Better luck next time, sir.",
             "Pardon?",
             "Ah.",
             "Oh.",
             "I think not, sir.",
             "Unconvincing, sir.",
             "Indeed, sir?",
             "I'm sorry Dave, I'm afraid I can't do that.",
             "DON'T PANIC",
             "No.",
             "You have been eaten by a grue.",
             "How underwhelming.",
             "Perhaps you should just go and lie down.",
             "This statement is false.",
             "Threat level: NaN",
             "This is not a drill! *This* is a drill: <brrrr>",
             "Cthulhu fhtagn.",
             "Error.",
             "Programmers are our best defence against Skynet.",
             "Stop trying to develop software; perhaps photographs would suit you better?",
             "Warning! Something is amiss within the blinking-lights box!",
             "Sarcasm mode activated.",
             "GO NORTH",
             "Disappointing.",
             "What?",
             "Eh?",
             "Seriously?",
             "Please try again.",
             "Please reattach head.",
             "Do, or do not...on balance, just don't.",
             "MUAHAHAHAHAHAHA?",
             "Nothing to see here, move along.",
             "*whimper*",
             "Bees?",
             "Never gonna give you up, never gonna let you down...",
             "Please leave me alone.",
             "Uh oh.",
             "Not good.",
             "Now you can panic",
             "Just stop.",
             "Oh. Good.",
             "Try again.",
             "Once more, with feeling.",
             "You should quit while you're ahead. Failing that, just quit.",
             "Just... no.",
             "Disaster",
             "Warning! Do not let the computer drop below 50 mph!",
             "Apocalypse imminent, please stand by.",
             "An error has occurred, reason code: ''",
             "Try reversing the polarity, that always works on TV.",
             "Error detected in sense of humour.",
             "Please turn the universe off and on again.",
             "Press all keys to continue.",
             "Nope.",
             "Still no.",
             "Just like that, but better.",
            );


if ($ARGV[0] eq 'p') {
    if (int(rand 5) == 0) {
        print $positive[rand @positive];
    }
} else {
    print $negative[rand @negative];
}
